# Generated by Django 4.2 on 2023-04-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletuser",
            name="is_premium_user",
            field=models.BooleanField(
                default=False,
                help_text="Select the checkbox to enjoy premium features.!",
                verbose_name="premium user",
            ),
        ),
    ]
