# Generated by Django 4.2 on 2023-04-22 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_walletuser_is_premium_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="walletuser",
            managers=[],
        ),
    ]
