# Generated by Django 4.2 on 2023-04-22 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "transaction_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="wallettransactions",
            old_name="sending_user",
            new_name="transaction_user",
        ),
        migrations.RemoveField(
            model_name="wallettransactions",
            name="charges_collecting_user",
        ),
        migrations.RemoveField(
            model_name="wallettransactions",
            name="receiving_charge_percentage",
        ),
        migrations.RemoveField(
            model_name="wallettransactions",
            name="receiving_charges_amount",
        ),
        migrations.RemoveField(
            model_name="wallettransactions",
            name="receiving_user",
        ),
        migrations.RemoveField(
            model_name="wallettransactions",
            name="sending_charge_percentage",
        ),
        migrations.RemoveField(
            model_name="wallettransactions",
            name="sending_charges_amount",
        ),
        migrations.AddField(
            model_name="wallettransactions",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wallettransactions",
            name="transaction_method",
            field=models.CharField(
                choices=[
                    ("debit", "Debit"),
                    ("credit", "Credit"),
                    ("charges", "Charges"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransactions",
            name="transaction_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.wallettransaction",
            ),
        ),
    ]
