# Generated by Django 4.2 on 2023-04-22 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_wallettransaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCharges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_type", models.CharField(max_length=20)),
                (
                    "sending_charge",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(25),
                        ],
                    ),
                ),
                (
                    "receiving_charge",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(25),
                        ],
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="wallettransaction",
            options={
                "verbose_name": "WalletTransactionID",
                "verbose_name_plural": "WalletTransactionIDs",
            },
        ),
        migrations.AlterModelOptions(
            name="wallettransactions",
            options={
                "verbose_name": "WalletTransactions",
                "verbose_name_plural": "WalletTransactions",
            },
        ),
    ]
