# Generated by Django 4.2 on 2023-04-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0004_wallettransaction_paying_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransactions",
            name="remarks",
            field=models.CharField(default="remarks", max_length=200),
            preserve_default=False,
        ),
    ]
